version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on: 
      - db
    environment:
      - "DJANGO_SECRET_KEY==db%=p_ynw+9q_#d6!9)-8ob78-i)xcbtc%f!h#o!ffw122r87"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
volumes:
  postgres_data: